### ISSUE TITLE
Failed test at cloned forked repo

### ISSUE THREAD

**Issue by odorifqi** [gabriel-pinheiro/bigodon#11]
i'm new at this, so i'm sorry if this is not what you expected.

so, i just cloned the repo from the forked one, and after i did `npm install` , i straight to `npm test` without doing any editing at the code. and i got error result.

![Screenshot (30)](https://user-images.githubusercontent.com/72656544/135779485-173eab49-2136-4c8b-a262-a09c2e51cdee.png)

Anf then i repeat the test and, it succesfully pass the test. 

![Screenshot (31)](https://user-images.githubusercontent.com/72656544/135779509-bee23e45-e4d1-4542-9078-522112d050fe.png)

From 5 test attempt, i got 2 success test. I didn't know if this happens because i cloned form the forked one. Because when i tested the clone from your account i got success test (even though i just doing it once).

**Comment by gabriel-pinheiro** [comment]
Hey @odorifqi 😄 

This is indeed a bug in the test, not the code. This test asserts that async helpers run one after the other instead of all at the same time.

The bug is: It does that using timing and values are way too low (20ms, 30ms). When the event loop is under high load (mainly because there are a lot of tests running), those timings might differ by quite a bit.

Would you like to open a PR fixing this issue? You can find the failing test [here](https://github.com/gabriel-pinheiro/bigodon/blob/main/test/helper.spec.js#L59-L68), just multiplying all those intervals by 10x (20 becomes 200, 30 becomes 300, 49 becomes 490, 59 becomes 590) would work because the tolerance would shift from 9ms to 90ms.

However, if you think of a different solution for this test, feel free to implement it instead!

**Comment by odorifqi** [comment]
yes, please. i want to open the PR. Thanks a lot for your kind and helpful response 😄

**Comment by odorifqi** [comment]
#12

**Comment by odorifqi** [comment]
#12
